spring:
  application:
    name: reservation
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  kafka:
    consumer:
      auto-offset-reset: earliest
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.apache.kafka: INFO
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
