spring:
  datasource:
    url: jdbc:mysql://app_mysql:3306/app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: app_user
    password: app_password
  data:
    redis:
      host: redis-server
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
