spring:
  datasource:
    url: jdbc:mysql://app_mysql:3306/app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: app_user
    password: app_password
  data:
    redis:
      host: redis-server
      port: 6379
  kafka:
    bootstrap-servers: kafka:9092
#  task:
#    execution:
#      pool:
#        core-size: 10       # 최소 Thread 수
#        max-size: 20        # 최대 Thread 수
#        queue-capacity: 50  # Thread Queue 크기
#  jpa:
#    hibernate:
#      jdbc:
#        batch_size: 50      # Hibernate Batch 처리 크기 조정
logging:
  level:
    root: info