spring:
  application:
    name: reservation
  datasource:
    url: jdbc:mysql://localhost:3307/app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: app_user
    password: app_password
  jpa:
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.apache.kafka: INFO
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
