spring:
  application:
    name: reservation

  datasource:
    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1;INIT=SET NAMES UTF8
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
      #properties:
      #hibernate.show_sql: true
    #hibernate.format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:/init/data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


