spring:
  application:
    name: reservation


  datasource:
    url: jdbc:mysql://localhost:3307/app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: app_user
    password: app_password

  jpa:
    hibernate:
      ddl-auto: update # 기존 테이블 유지하며 변경 사항 업데이트
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect # MySQL8 전용 Dialect
    defer-datasource-initialization: true

#    sql:
#      init:
#        mode: always
#        schema-locations: classpath:/init/data.sql # 초기화 스크립트 경로

  h2:
    console:
      enabled: false # H2 콘솔 비활성화

  data:
    redis:
      host: localhost
      port: 6379

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

      #  datasource:
      #    url: jdbc:h2:mem:db;MODE=MYSQL;DB_CLOSE_DELAY=-1;INIT=SET NAMES UTF8
      #    driver-class-name: org.h2.Driver
      #    username: sa
      #    password: ""

      #  jpa:
      #    hibernate:
      #      ddl-auto: create-drop
      #    defer-datasource-initialization: true
      #properties:
      #hibernate.show_sql: true
    #hibernate.format_sql: true
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:/init/data.sql

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

#spring:
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:/init/schema.sql
#      data-locations: classpath:/init/data.sql