server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/app_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: app_user
    password: app_password
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092
