version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # 로컬 포트 6379와 Redis 컨테이너 포트를 연결

  mysql:
    image: mysql:8.0.33
    container_name: mysql_test_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_db
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword
    ports:
      - "3306:3306"  # 로컬 포트 3306과 MySQL 컨테이너 포트를 연결
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터 영구 저장
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  mysql_data: